sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vennilasanthanam/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vennilasanthanam/react-test npm test

after_success:
  - docker build -t vennilasanthanam/multi-client ./client
  - docker build -t vennilasanthanam/multi-nginx ./nginx
  - docker build -t vennilasanthanam/multi-server ./server
  - docker build -t vennilasanthanam/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vennilasanthanam/multi-client
  - docker push vennilasanthanam/multi-nginx
  - docker push vennilasanthanam/multi-server
  - docker push vennilasanthanam/multi-worker
deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "multi-docker"
    env: "Multi-docker-env"
    bucket_name: "elasticbeanstalk-us-east-1-992382774185"
    bucket_path: "docker-multi"
    on:
       branch: main  
       access_key_id: "$AWS_ACCESS_KEY"
       secrets_access_key: "$AWS_SECRET_KEY"
      